/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bugreportingtool;

import code.DataBase;
import java.awt.Toolkit;
import java.io.File;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author mahim
 */
public class ReportPage extends javax.swing.JFrame {

    /**
     * Creates new form ReportPage
     */
    public ReportPage() {
        initComponents();
        dateTime();
        setIconImage();
    }
    public void dateTime(){
    LocalDateTime myDateObj = LocalDateTime.now();
    
    DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");

    String formattedDate = myDateObj.format(myFormatObj);
    datetime.setText(""+formattedDate);
    }
    private void setIconImage(){
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("antivirus.png")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        dateLbl = new javax.swing.JLabel();
        datetime = new javax.swing.JLabel();
        testerNameLbl = new javax.swing.JLabel();
        testerName = new javax.swing.JTextField();
        devLbl = new javax.swing.JLabel();
        devName = new javax.swing.JTextField();
        BugTLbl = new javax.swing.JLabel();
        bugTitle = new javax.swing.JTextField();
        BidLbl = new javax.swing.JLabel();
        bugId = new javax.swing.JTextField();
        statusLbl = new javax.swing.JLabel();
        jStatus = new javax.swing.JComboBox<>();
        sumLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        summary = new javax.swing.JTextArea();
        addFile = new javax.swing.JButton();
        Submit = new javax.swing.JButton();
        fileName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Report Bug");
        setLocationByPlatform(true);

        jPanel1.setBackground(new java.awt.Color(104, 176, 171));

        btnBack.setBackground(new java.awt.Color(236, 244, 243));
        btnBack.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        dateLbl.setBackground(new java.awt.Color(236, 244, 243));
        dateLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        dateLbl.setText("Date: ");

        datetime.setBackground(new java.awt.Color(236, 244, 243));
        datetime.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        datetime.setText("hjgvjhjk");

        testerNameLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        testerNameLbl.setText("Tester Name:");

        testerName.setBackground(new java.awt.Color(236, 244, 243));
        testerName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        devLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        devLbl.setText("Developer name: ");

        devName.setBackground(new java.awt.Color(236, 244, 243));
        devName.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        devName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                devNameActionPerformed(evt);
            }
        });

        BugTLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        BugTLbl.setText("Bug Title: ");

        bugTitle.setBackground(new java.awt.Color(236, 244, 243));
        bugTitle.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        bugTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugTitleActionPerformed(evt);
            }
        });

        BidLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        BidLbl.setText("BugID:");

        bugId.setBackground(new java.awt.Color(236, 244, 243));
        bugId.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        bugId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bugIdActionPerformed(evt);
            }
        });

        statusLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        statusLbl.setText("Status:");

        jStatus.setBackground(new java.awt.Color(236, 244, 243));
        jStatus.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        jStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Status", "New", "Rejected", "Deffered", "Duplicate", "In Progress..", "Fixed", "Closed", "Reopen" }));
        jStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jStatusActionPerformed(evt);
            }
        });

        sumLbl.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        sumLbl.setText("Summary: ");

        summary.setBackground(new java.awt.Color(236, 244, 243));
        summary.setColumns(20);
        summary.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        summary.setRows(5);
        jScrollPane1.setViewportView(summary);

        addFile.setBackground(new java.awt.Color(236, 244, 243));
        addFile.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N
        addFile.setText("Add Photo");
        addFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addFileActionPerformed(evt);
            }
        });

        Submit.setText("Submit");
        Submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitActionPerformed(evt);
            }
        });

        fileName.setEditable(false);
        fileName.setBackground(new java.awt.Color(236, 244, 243));
        fileName.setFont(new java.awt.Font("Tw Cen MT", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(addFile)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fileName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(sumLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(statusLbl)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnBack)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(testerNameLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(testerName, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BugTLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bugTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(27, 27, 27)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(BidLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bugId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(dateLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(devLbl)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(devName, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(55, 55, 55))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Submit, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(248, 248, 248))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(datetime, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateLbl))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(testerNameLbl)
                    .addComponent(testerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(devLbl)
                    .addComponent(devName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BugTLbl)
                    .addComponent(bugTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BidLbl)
                    .addComponent(bugId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(statusLbl)
                    .addComponent(jStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sumLbl)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fileName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addFile))
                .addGap(18, 21, Short.MAX_VALUE)
                .addComponent(Submit)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bugIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bugIdActionPerformed

    private void jStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jStatusActionPerformed

    private void addFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addFileActionPerformed
        // TODO add your handling code here:
        JFileChooser upload = new JFileChooser();
        upload.showOpenDialog(null);
        File file = upload.getSelectedFile();
        
        String filename = upload.getSelectedFile().getName();
        fileName.setText(filename);
        path = file.getAbsolutePath();
        

    }//GEN-LAST:event_addFileActionPerformed

    private void getData(){
         tname = testerName.getText();
         dName = devName.getText();
         id = bugId.getText();
         title = bugTitle.getText();
         smry = summary.getText();
         dateTime();
         dt = datetime.getText();
         status = jStatus.getSelectedItem().toString();
    }
    private void SubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Submit")== 0){
        getData();
        DataBase bd = new DataBase();
        bd.insertion(id,title,smry,dt,status,path,tname,dName);
        clearData();
        }else{
        JOptionPane.showMessageDialog(this, "Not Submitted");
        }

        
    }//GEN-LAST:event_SubmitActionPerformed
    private void clearData(){
        bugId.setText("");
        bugTitle.setText("");
        devName.setText("");
        fileName.setText("");
        summary.setText("");
        testerName.setText("");
        jStatus.setSelectedIndex(0);

    }
    private void devNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_devNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_devNameActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        new SelectionPage().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void bugTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bugTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bugTitleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReportPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReportPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BidLbl;
    private javax.swing.JLabel BugTLbl;
    private javax.swing.JButton Submit;
    private javax.swing.JButton addFile;
    private javax.swing.JButton btnBack;
    private javax.swing.JTextField bugId;
    private javax.swing.JTextField bugTitle;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel datetime;
    private javax.swing.JLabel devLbl;
    private javax.swing.JTextField devName;
    private javax.swing.JTextField fileName;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jStatus;
    private javax.swing.JLabel statusLbl;
    private javax.swing.JLabel sumLbl;
    private javax.swing.JTextArea summary;
    private javax.swing.JTextField testerName;
    private javax.swing.JLabel testerNameLbl;
    // End of variables declaration//GEN-END:variables
byte[] photo=null;
String filename=null, path = null,dt = null,smry = null ,title = null,id = null,dName = null,tname = null, status = null;

}
